"""Dictionaries used to link between systems."""

# Definition of the OpenBIS collection
premise3_collection = [
    {
        "metadata": "Sample ID",
        "openbis_code": "p3_sample_id",
        "description": "Unique identifier for the sample",
        "type": "VARCHAR",
    },
    {
        "metadata": "Run ID",
        "openbis_code": "p3_run_id",
        "description": "Unique identifier for the run",
        "type": "VARCHAR",
    },
    {
        "metadata": "Cell number",
        "openbis_code": "p3_cell_number",
        "description": "Cell number within the run",
        "type": "REAL",
    },
    {
        "metadata": "Actual N:P ratio",
        "openbis_code": "p3_actual_np_ratio",
        "description": "The N:P ratio of the cell taking into account overlap, i.e. the ratio of areal capacities",
        "type": "REAL",
    },
    {
        "metadata": "Rack position",
        "openbis_code": "p3_rack_position",
        "description": "Well number of non-electrode components within racks of the robot",
        "type": "REAL",
    },
    {
        "metadata": "Separator",
        "openbis_code": "p3_separator",
        "description": "Type of separator used",
        "type": "VARCHAR",
    },
    {
        "metadata": "Electrolyte name",
        "openbis_code": "p3_electrolyte_name",
        "description": "Name of the electrolyte",
        "type": "VARCHAR",
    },
    {
        "metadata": "Electrolyte description",
        "openbis_code": "p3_electrolyte_description",
        "description": "Description of the electrolyte",
        "type": "VARCHAR",
    },
    {
        "metadata": "Electrolyte position",
        "openbis_code": "p3_electrolyte_position",
        "description": "Position of the electrolyte in the robot",
        "type": "REAL",
    },
    {
        "metadata": "Electrolyte amount (uL)",
        "openbis_code": "p3_electrolyte_amount_ul",
        "description": "Amount of electrolyte used in microliters",
        "type": "REAL",
    },
    {
        "metadata": "Electrolyte dispense order",
        "openbis_code": "p3_electrolyte_dispense_order",
        "description": "Order of electrolyte dispensing, before separator, after or both",
        "type": "VARCHAR",
    },
    {
        "metadata": "Electrolyte amount before separator (uL)",
        "openbis_code": "p3_electrolyte_amount_before_separator_ul",
        "description": "Electrolyte amount before the separator in microliters",
        "type": "REAL",
    },
    {
        "metadata": "Electrolyte amount after separator (uL)",
        "openbis_code": "p3_electrolyte_amount_after_separator_ul",
        "description": "Electrolyte amount after the separator in microliters",
        "type": "REAL",
    },
    {
        "metadata": "Anode type",
        "openbis_code": "p3_anode_type",
        "description": "Type of anode used",
        "type": "VARCHAR",
    },
    {
        "metadata": "Anode description",
        "openbis_code": "p3_anode_description",
        "description": "Description of the anode",
        "type": "VARCHAR",
    },
    {
        "metadata": "Anode rack position",
        "openbis_code": "p3_anode_rack_position",
        "description": "Anode well number within rack of the robot",
        "type": "REAL",
    },
    {
        "metadata": "Anode diameter (mm)",
        "openbis_code": "p3_anode_diameter_mm",
        "description": "Diameter of the anode in millimeters",
        "type": "REAL",
    },
    {
        "metadata": "Anode mass (mg)",
        "openbis_code": "p3_anode_mass_mg",
        "description": "Mass of the anode in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Anode current collector mass (mg)",
        "openbis_code": "p3_anode_current_collector_mass_mg",
        "description": "Mass of the anode current collector in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Anode active material mass fraction",
        "openbis_code": "p3_anode_active_material_mass_fraction",
        "description": "Mass fraction of active material in the anode",
        "type": "REAL",
    },
    {
        "metadata": "Anode active material mass (mg)",
        "openbis_code": "p3_anode_active_material_mass_mg",
        "description": "Mass of active material in the anode in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Anode C-rate definition areal capacity (mAh/cm2)",
        "openbis_code": "p3_anode_crate_definition_areal_capacity_mahcm2",
        "description": "Areal capacity in mAh/cm2 for the anode used to define the C-rate ",
        "type": "REAL",
    },
    {
        "metadata": "Anode C-rate definition specific capacity (mAh/g)",
        "openbis_code": "p3_anode_crate_definition_specific_capacity_mahg",
        "description": "Specific capacity in mAh/g for the anode used to define the C-rate",
        "type": "REAL",
    },
    {
        "metadata": "Anode balancing specific capacity (mAh/g)",
        "openbis_code": "p3_anode_balancing_specific_capacity_mahg",
        "description": "Specific capacity in mAh/g for the anode used for N:P ratio calculation",
        "type": "REAL",
    },
    {
        "metadata": "Anode balancing capacity (mAh)",
        "openbis_code": "p3_anode_balancing_capacity_mah",
        "description": "Capacity in mAh for the anode used for N:P ratio calculation",
        "type": "REAL",
    },
    {
        "metadata": "Cathode type",
        "openbis_code": "p3_cathode_type",
        "description": "Type of cathode used",
        "type": "VARCHAR",
    },
    {
        "metadata": "Cathode rack position",
        "openbis_code": "p3_cathode_rack_position",
        "description": "Cathode well number within rack of the robot",
        "type": "REAL",
    },
    {
        "metadata": "Cathode description",
        "openbis_code": "p3_cathode_description",
        "description": "Description of the cathode",
        "type": "VARCHAR",
    },
    {
        "metadata": "Cathode diameter (mm)",
        "openbis_code": "p3_cathode_diameter_mm",
        "description": "Diameter of the cathode in millimeters",
        "type": "REAL",
    },
    {
        "metadata": "Cathode mass (mg)",
        "openbis_code": "p3_cathode_mass_mg",
        "description": "Mass of the cathode in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Cathode current collector mass (mg)",
        "openbis_code": "p3_cathode_current_collector_mass_mg",
        "description": "Mass of the cathode current collector in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Cathode active material mass fraction",
        "openbis_code": "p3_cathode_active_material_mass_fraction",
        "description": "Mass fraction of active material in the cathode",
        "type": "REAL",
    },
    {
        "metadata": "Cathode active material mass (mg)",
        "openbis_code": "p3_cathode_active_material_mass_mg",
        "description": "Mass of active material in the cathode in milligrams",
        "type": "REAL",
    },
    {
        "metadata": "Cathode C-rate definition areal capacity (mAh/cm2)",
        "openbis_code": "p3_cathode_crate_definition_areal_capacity_mahcm2",
        "description": "Areal capacity in mAh/cm2 for the cathode used to define the C-rate",
        "type": "REAL",
    },
    {
        "metadata": "Cathode C-rate definition specific capacity (mAh/g)",
        "openbis_code": "p3_cathode_crate_definition_specific_capacity_mahg",
        "description": "Specific capacity in mAh/g for the cathode used to define the C-rate",
        "type": "REAL",
    },
    {
        "metadata": "Cathode balancing specific capacity (mAh/g)",
        "openbis_code": "p3_cathode_balancing_specific_capacity_mahg",
        "description": "Specific capacity in mAh/g for the cathode used for N:P ratio calculation",
        "type": "REAL",
    },
    {
        "metadata": "Cathode balancing capacity (mAh)",
        "openbis_code": "p3_cathode_balancing_capacity_mah",
        "description": "Capacity in mAh for the cathode used for N:P ratio calculation",
        "type": "REAL",
    },
    {
        "metadata": "C-rate definition capacity (mAh)",
        "openbis_code": "p3_crate_definition_capacity_mah",
        "description": "Capacity in mAh used to define the C-rate",
        "type": "REAL",
    },
    {
        "metadata": "N:P ratio overlap factor",
        "openbis_code": "p3_np_ratio_overlap_factor",
        "description": "Overlap factor of anode and cathode, used to calculate N:P ratio",
        "type": "REAL",
    },
    {
        "metadata": "Casing type",
        "openbis_code": "p3_casing_type",
        "description": "Type of casing used",
        "type": "VARCHAR",
    },
    {
        "metadata": "Separator diameter (mm)",
        "openbis_code": "p3_separator_diameter_mm",
        "description": "Diameter of the separator in millimeters",
        "type": "REAL",
    },
    {
        "metadata": "Spacer (mm)",
        "openbis_code": "p3_spacer_mm",
        "description": "Size of the spacer in millimeters",
        "type": "REAL",
    },
    {
        "metadata": "Comment",
        "openbis_code": "p3_comment",
        "description": "Comments from robot assembly",
        "type": "VARCHAR",
    },
    {
        "metadata": "Barcode",
        "openbis_code": "p3_barcode",
        "description": "Barcode of the cell",
        "type": "VARCHAR",
    },
]

# Map between metadata in the analyzed json file and the openbis code
dict_json_to_openbis = {j["metadata"]: j["openbis_code"] for j in premise3_collection}

# This dictionary maps between the metadata column in the excel/ontology and the analyzed json file.
dict_excel_to_json = {
    "Cell ID": "Sample ID",
    "Separator manufacturer": "Separator",
    "Electrolyte manufacturer": "Electrolyte name",
    "Negative electrode coating active material": "Anode type",
    "Negative electrode diameter": "Anode diameter (mm)",
    "Negative electrode coating active material mass fraction": "Anode active material mass fraction",
    "Positive electrode coating active material": "Cathode type",
    "Positive electrode diameter": "Cathode diameter (mm)",
    "Positive electrode coating active material mass fraction": "Cathode active material mass fraction",
    "Cell case": "Casing type",
    "Separator diameter": "Separator diameter (mm)",
}
